-- Minimal SQL schema bootstrap (PostgreSQL).
-- This repo also auto-creates tables on startup via `app/core/database.py:init_db()`.
-- Use this script if you want a deterministic SQL initialization step.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(50) NOT NULL UNIQUE,
  hashed_password VARCHAR(255) NOT NULL,
  subscription_tier VARCHAR(20) NOT NULL DEFAULT 'BASE',
  plan VARCHAR(20) NOT NULL DEFAULT 'base',
  stripe_customer_id VARCHAR(255),
  stripe_subscription_id VARCHAR(255),
  plan_status VARCHAR(20),
  plan_renews_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);
CREATE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE INDEX IF NOT EXISTS ix_users_plan ON users (plan);
CREATE INDEX IF NOT EXISTS ix_users_stripe_customer_id ON users (stripe_customer_id);
CREATE INDEX IF NOT EXISTS ix_users_stripe_subscription_id ON users (stripe_subscription_id);
CREATE INDEX IF NOT EXISTS ix_users_plan_status ON users (plan_status);

CREATE TABLE IF NOT EXISTS roster_states (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  cards JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roster_cards (
  id VARCHAR(80) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  tags TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_roster_cards_user_id ON roster_cards (user_id);

CREATE TABLE IF NOT EXISTS chat_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255),
  roster_card_id VARCHAR(80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_chat_threads_user_id ON chat_threads (user_id);
CREATE INDEX IF NOT EXISTS ix_chat_threads_roster_card_id ON chat_threads (roster_card_id);
CREATE INDEX IF NOT EXISTS ix_chat_threads_updated_at ON chat_threads (updated_at);
CREATE INDEX IF NOT EXISTS ix_chat_threads_user_roster_updated ON chat_threads (user_id, roster_card_id, updated_at);

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  image_url VARCHAR(500),
  image_mime_type VARCHAR(100),
  image_size_bytes INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_chat_messages_thread_id ON chat_messages (thread_id);
CREATE INDEX IF NOT EXISTS ix_chat_messages_thread_created_at ON chat_messages (thread_id, created_at);


